module.exports = [
    'Open Sans',
    'Roboto',
    'Slabo27px',
    'Lato',
    'Oswald',
    'Roboto Condensed',
    'Source Sans Pro',
    'Montserrat',
    'Raleway',
    'PT Sans',
    'Lora',
    'Roboto Slab',
    'Open Sans Condensed',
    'Droid Sans',
    'Droid Serif',
    'Arimo',
    'Merriweather',
    'PT Sans Narrow',
    'Fjalla One',
    'Noto Sans',
    'PT Serif',
    'Titillium Web',
    'Playfair Display',
    'Muli',
    'Indie Flower',
    'Alegreya Sans',
    'Bitter',
    'Dosis',
    'Oxygen',
    'Cabin',
    'Inconsolata',
    'Poiret One',
    'Yanone Kaffeesatz',
    'Lobster',
    'Candal',
    'Passion One',
    'Hind',
    'Arvo',
    'Noto Serif',    
    'Nunito',
    'Bree Serif',
    'Josefin Sans',
    'Covered By Your Grace',
    'Abel',
    'Exo 2',
    'Libre Baskerville',
    'Asap',
    'Merriweather Sans',
    'Pacifico',
    'Poppins',
    'Quicksand',
    'Crimson Text',
    'Varela Round'    
];